import * as React from "react";
import "./premium.css";
import NavBar from "../../GeneralComponents/NavBar/navbar";
import Footer from "../../GeneralComponents/Footer/footer";
import premium from "../../../assets/images/premiumImg.png";

const Premium = () => {
  return (
    <>
      <NavBar />
      <div className="premiumsectionOne generalContainer">
        <h1 className="premiumsectionOneTtl">
          INTERNIFY <span>OFFERINGS</span>
        </h1>
        <div className="premiumsectionOneWrap">
          <div className="premiumsectionOneInfo">
            <h5 className="premiumsectionOneInfottl">
              A whole world of opportunities await you
            </h5>
            <ul className="premiumsectionOneInfoList">
              <li>
                <h6 className="premiumsectionOneInfoListItemHd">
                  Unlimited job searches
                </h6>
                <p className="premiumsectionOneInfoListItemTxt">
                  Registering for internify premium grants you access to
                  unlimited searches
                </p>
              </li>
              <li>
                <h6 className="premiumsectionOneInfoListItemHd">
                  Affiliate marketing job
                </h6>
                <p className="premiumsectionOneInfoListItemTxt">
                  Earn as a premium member by sharing your link with friends
                </p>
              </li>
              <li>
                <h6 className="premiumsectionOneInfoListItemHd">
                  CV generator
                </h6>
                <p className="premiumsectionOneInfoListItemTxt">
                  Get customised cv generated by Internify network.
                </p>
              </li>
              <li>
                <h6 className="premiumsectionOneInfoListItemHd">
                  Access to skill courses
                </h6>
                <p className="premiumsectionOneInfoListItemTxt">
                  Available on the app, get skill enhancing courses for free
                </p>
              </li>
              <li>
                <h6 className="premiumsectionOneInfoListItemHd">
                  Webinars with educationists
                </h6>
                <p className="premiumsectionOneInfoListItemTxt">
                  Zoom conference organised for the premium members.
                </p>
              </li>
            </ul>
          </div>
          <img className="premiumsectionOneImg" src={premium} alt="" />
        </div>
      </div>
      <div className="premiumSectionTwo generalContainer">
        <h5 className="premiumSectionTwoTxt">Please fill in the form below to proceed</h5>
        <form className="premiumSectionTwoForm">
          <label>
            Internify Name:
            <input className="internify-input" type="text" />
          </label>
          <label>
            Internify Password:
            <input className="internify-input" type="password" />
          </label>
          <button className="premiumSectionTwoBtn appBtnFill">Proceed</button>
        </form>
      </div>
      <Footer />
    </>
  );
};

export default Premium;
